sudo docker kill core
sudo docker rm core
sudo docker rmi image/core
sudo docker kill appjson
sudo docker rm appjson
sudo docker rmi image/appjson
sudo docker kill appjson
sudo docker rm appjson
sudo docker rmi image/appjson
sudo docker kill banco
sudo docker rm banco
sudo docker rmi image/banco
